#!/usr/bin/env zsh

RED="\033[1;31m";
GREEN="\033[1;32m";
BLUE="\033[36m";
YELLOW="\033[33m";
NOCL="\033[m";

# ------------------------------------------------------------------------------------------
#
#	 Читаем значение переменной из ввода данных в цикле
#	 $1 - заголовок для запроса
#	 $2 - переменная в которой возвращается результат
#	 $3 - тип вводимого значения
#		 digit - цифра
#		 password - пароль без показа вводимых символов
#
# ------------------------------------------------------------------------------------------
read_value() {
	header="$(echo "${1}" | tr -d '?:')"
	type="${3}"
	while true; do
		echo -n "${BLUE}${header}${NOCL}: "
		read value
		if [ -z "${value}" ]; then
				echo
				print_line
				echo -e "${RED}Данные не должны быть пустыми!"
				echo -e "${GREEN}Попробуйте ввести значение снова...${NOCL}"
				print_line
		elif echo "${value}" | grep -qiE '^Q$' ; then
				eval "${2}=q"
				break
		elif [ "${type}" = 'digit' ] && ! echo "${value}" | grep -qE '^[[:digit:]]{1,6}$'; then
				echo
				print_line
				echo -e "${RED}Введенные данные должны быть цифрами!"
				echo -e "${GREEN}Попробуйте ввести значение снова...${NOCL}"
				print_line
		else
				eval "${2}=${value}"
				break
		fi
	done
}

print_line() {
	len=65
	printf "%${len}s\n" | tr " " "="
}

# В случае если не были введены данные токена
! [ -f ./.conf ] && {
	macbook=''; read_value "Введите имя вашего макбука" macbook
	max=''; read_value "Введите верхний порог зарядки макбука" max
	min=''; read_value "Введите нижний порог разрядки макбука" min
	token=''; read_value "Введите token Телеграм бота" token
	id=''; read_value "Введите id диалога в Телеграм боте" id
	period=''; read_value "Введите период опроса состояния батареи" period digit
	print_line
	echo -n 'Установка пакета macbat завершена                '

	echo "token=${token}" > ./.conf
	echo "id=${id}" >> ./.conf
	echo "notebook_name=${macbook}" >> ./.conf
	echo "max=${max}" >> ./.conf
	echo "min=${min}" >> ./.conf

	cron_file=./crontab.tmp
   	crontab -l > ${cron_file}
	sed -i -e '/macbat/d' ${cron_file}
	echo "*/${period}    *    *   *   *    $(pwd)/macbat &" >> ${cron_file}
	crontab < "${cron_file}"
	rm ${cron_file}

	[ $? = 0 ] && echo 'УСПЕШНО' || echo 'С ОШИБКАМИ'
	print_line

}

